import { useState, useCallback } from 'react';
import { type MidnightProviders } from '@midnight-ntwrk/midnight-js-types';
import { Contract, type ContractAddress } from '@midnight-ntwrk/midnight-js-contracts';
import { httpClientProofProvider } from '@midnight-ntwrk/dapp-connector-proof-provider';
import type { DAppConnectorAPI, DAppConnectorWalletAPI } from '@midnight-ntwrk/dapp-connector-api';

// @ts-ignore - Assuming managed folder is generated by the compiler
import { Contract as PayEchoContract, payecho } from '../../managed/payecho';
import config from '../config/contract-config.json';

export function useMidnight() {
    const [isWalletConnected, setIsWalletConnected] = useState(false);
    const [walletAddress, setWalletAddress] = useState<string | null>(null);
    const [contractInstance, setContractInstance] = useState<PayEchoContract<any> | null>(null);
    const [bandCounts, setBandCounts] = useState({ band1: 0, band2: 0, band3: 0 });
    const [statusMessage, setStatusMessage] = useState('');
    const [isSubmitting, setIsSubmitting] = useState(false);

    // Disconnect logic
    const disconnectWallet = useCallback(() => {
        setIsWalletConnected(false);
        setWalletAddress(null);
        setContractInstance(null);
        setStatusMessage('Wallet disconnected.');
    }, []);

    const updateStatsUI = useCallback(async (instance: PayEchoContract<any>) => {
        try {
            const state = await instance.queryState();
            setBandCounts({
                band1: Number(state.bandCounters?.get?.(1n) || 0n),
                band2: Number(state.bandCounters?.get?.(2n) || 0n),
                band3: Number(state.bandCounters?.get?.(3n) || 0n),
            });
        } catch (e) {
            console.error("Error querying state:", e);
        }
    }, []);

    const connectWallet = useCallback(async () => {
        try {
            setStatusMessage('Connecting to 1AM Wallet...');
            
            // Polling for window.midnight to allow extension injection
            const getMidnight = (): Promise<any> => {
                return new Promise((resolve, reject) => {
                    let attempts = 0;
                    const interval = setInterval(() => {
                        const mn = (window as any).midnight;
                        if (mn && (mn.mn1am || mn.mnLace)) {
                            clearInterval(interval);
                            console.log("[Midnight Diagnostics] Wallet object detected on window.");
                            resolve(mn);
                        }
                        attempts++;
                        if (attempts >= 20) { // 2 seconds max
                            clearInterval(interval);
                            reject(new Error("Wallet extension not found. Please install 1AM or Lace."));
                        }
                    }, 100);
                });
            };

            const midnight = await getMidnight();
            const connector = midnight.mn1am || midnight.mnLace;
            const wallet: DAppConnectorWalletAPI = await connector.enable();
            
            console.log("[Midnight Diagnostics] Connected to wallet API.");
            
            // Subscribe to wallet state changes if supported by the DApp Connector
            if (wallet.state && typeof wallet.state().subscribe === 'function') {
                wallet.state().subscribe((state: any) => {
                    setWalletAddress(state.address || state.publicAddress || '0x... connected');
                    // Handle disconnect from wallet side
                    if (state.status === 'disconnected') {
                        setIsWalletConnected(false);
                        setContractInstance(null);
                    }
                });
            } else {
                // Fallback if no observable state is provided
                setWalletAddress('0x1AM...Connected');
            }
            
            let networkConfig: any = {};
            if (typeof connector.getConfiguration === 'function') {
                networkConfig = await connector.getConfiguration();
                console.log("[Midnight Diagnostics] Fetched Wallet Configuration:", networkConfig);
            } else {
                console.log("[Midnight Diagnostics] Fetched Wallet Configuration: (Mocked/Default)");
            }
            
            const midnightProviders: MidnightProviders = {
                privateStateProvider: wallet.privateStateProvider,
                zkConfigProvider: wallet.zkConfigProvider,
                publicDataProvider: wallet.publicDataProvider,
                proofProvider: wallet.proofProvider || httpClientProofProvider(networkConfig?.proofServerUrl || 'http://127.0.0.1:6300'),
                walletProvider: wallet.walletProvider,
            };

            const contractAddress = config.contractAddress as ContractAddress;
            
            if (contractAddress) {
                const instance = await Contract.build(
                    midnightProviders,
                    contractAddress,
                    payecho.contractConfig
                );
                setContractInstance(instance);
                await updateStatsUI(instance);
                console.log("[Midnight Diagnostics] Contract successfully instantiated and synced.");
            }
            
            setIsWalletConnected(true);
            setStatusMessage('Wallet connected successfully!');
        } catch (error: any) {
            setStatusMessage(error.message || 'Failed to connect wallet.');
            setIsWalletConnected(false);
        }
    }, [updateStatsUI]);

    const submitSalary = useCallback(async (salary: number, saltString: string) => {
        try {
            if (isNaN(salary) || salary < 0) {
                throw new Error("Invalid salary amount.");
            }
            
            if (!contractInstance) {
                throw new Error("Contract not connected.");
            }

            setIsSubmitting(true);
            setStatusMessage('Proving salary band in ZK without revealing amount...');

            const saltBytes = new TextEncoder().encode(saltString.padEnd(32, '\0')).slice(0, 32);

            const tx = await contractInstance.callTx.submitSalary({
                local_salary: () => BigInt(salary),
                local_salt: () => saltBytes
            });
            
            await tx.wait();
            await updateStatsUI(contractInstance);

            setStatusMessage('Salary benchmark contributed anonymously!');
            setIsSubmitting(false);
        } catch (error: any) {
            setStatusMessage(error.message || 'Failed to submit proof.');
            setIsSubmitting(false);
        }
    }, [contractInstance, updateStatsUI]);

    return {
        isWalletConnected,
        walletAddress,
        connectWallet,
        disconnectWallet,
        submitSalary,
        bandCounts,
        statusMessage,
        isSubmitting
    };
}
